JS-303: Object-Oriented JavaScript
cbins13/dotTheory---JavaScript pull request #10
Opened 2022-08-15 11:03 UTC by cbins13

## Related Tickets
- JS-264

## Description
- This pull request is created for the module JS-3013 where the parent folder named after the module contains the final code solutions for the Code Challenge quizzes.

## Validation
- Clone the repository using SSH or HTTPS
- Open the folder named JS-303 after cloning the repository
- You will find one folder containing the final code solutions for each code challenge quiz, namely:
--OOJS_Course
---Adding Methods to Classes
---Changing and Adding Properties
---Creating a New Class
---Creating Getter Methods
---Creating Object Literals
---Creating Setter Methods
---Filling out the Play Method
---Instantiating an Object

--OOJS Challenge Course
---css
---js

2022-09-30 10:21 UTC, athanph commented on JS-303/OOJS_Challenge_Course/Complete_Project/css/style.css
> +#game-scene {
In real-life projects, `id`s are not meant to be used for styling due to their high specificity and maintainability issues. No need to update, though

2022-09-30 10:27 UTC, athanph commented on JS-303/OOJS_Challenge_Course/Complete_Project/js/Game.js
> +      player.active = player.active ? false : true;
You can simplify this with `player.active = !player.active;` If value is true, then `!` aka "bang" will reverse it making it false

2022-09-30 10:36 UTC, athanph commented on JS-303/OOJS_Course/4_Getters_and_Setters/Creating_Getter_Methods/creating_getters.js
> +        if(this.credits > 90){
Since you are early returning, you can get rid of `else` keyword, Or better yet do a `swtich`.

2022-09-30 10:37 UTC, athanph requested changes
@cbins13 Left some comments to address

2022-10-07 09:33 UTC, cbins13 commented
> @cbins13 Left some comments to address

Added commits resolving comments provided to the code review.

2022-10-10 10:28 UTC, athanph commented on JS-303/OOJS_Course/4_Getters_and_Setters/Creating_Getter_Methods/creating_getters.js
> +    switch (true) {
@cbins13 Instead of `true`, you should pass the expression to be evaluated here which is `studCreds`.

2022-10-10 10:32 UTC, athanph commented on JS-303/OOJS_Course/4_Getters_and_Setters/Creating_Getter_Methods/creating_getters.js
> +      case studCreds <= 30:
Including a `default` is always recommended as a fallback in case of no match. You can make the last case the default.

2022-10-10 10:38 UTC, athanph commented on JS-303/OOJS_Course/4_Getters_and_Setters/Creating_Getter_Methods/creating_getters.js
> +    switch (true) {
Never mind. I recognized late that you're doing the switch true pattern.

2022-10-10 10:41 UTC, athanph approved these changes

2022-10-10 10:41 UTC, merged