JS-402: Express Basics (Christian Binay-an)
cbins13/dotTheory---JavaScript pull request #12
Opened 2022-08-22 09:51 UTC by cbins13

## Related Tickets

- JS-266

## Description
- This pull request is created for the module JS-402 where the parent folder named after the module contains the final code solutions for the Code Challenge quizzes.

## Validation
- Clone the repository using SSH or HTTPS
- Open the folder named JS-402 after cloning the repository
- You will find one folder containing the final code solutions for each code challenge quiz, namely:
-- Asynchronouse Code in Express
-- Debug Node Applications with VS Code
-- Express Basics Course
-- REST APIs with Express
-- Using Sequelize ORM with Express
-- Using SQL ORMs with Nodejs

2022-10-06 10:05 UTC, athanph commented
@cbins13 `node_modules` should never be included in a PR. Kindly add it to .gitignore to reduce the number of files.

2022-10-06 10:05 UTC, athanph requested changes
Remove node_modules folder

2022-10-07 08:48 UTC, cbins13 commented
> @cbins13 `node_modules` should never be included in a PR. Kindly add it to .gitignore to reduce the number of files.

Edited .gitignore file



> Remove node_modules folder, VSCode files, and .DSstore files

Removed node_modules folders, .vscode files, and .DS_Store files

2022-10-10 11:07 UTC, athanph approved these changes

2022-10-10 11:07 UTC, merged